# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Seoul"
    target-branch: "master"
    commit-message:
      prefix: "[.NET]"
    groups:
      microsoft-extensions:
        dependency-type: "development"
        applies-to: version-updates
        patterns:
        - "Microsoft.Extensions.*"
        update-types:
        - "minor"
        - "patch"
      normal-deps:
        dependency-type: "development"
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "major"
        - "minor"
        - "patch"
        exclude-patterns:
        - "Microsoft.Extensions.*"

    ignore:
    - dependency-name: "Microsoft.Extensions.*"
      update-types: ["version-update:semver-major"]